version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/whaleTracker
permissions:
  - object: /home/ec2-user/whaleTracker
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  ApplicationStop:
    - location: codedeploy/app_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: codedeploy/before_install_root.sh
      timeout: 120
      runas: root
    - location: codedeploy/before_install_user.sh
      timeout: 120
      runas: ec2-user
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 480
      runas: ec2-user
  ApplicationStart:
    - location: codedeploy/app_start.sh
      timeout: 300
      runas: ec2-user
#  ValidateService:
#    - location: codedeploy/validate_service.sh
#      timeout: 180

