# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo NODE_ENV $NODE_ENV
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run webpack
      - npm run build
      - ls -la
  post_build:
    commands:
      - echo Build completed on `date`
#cache:
#  paths:
#    - 'node_modules/**/*'
artifacts:
  files:
    - appspec.yml
    - ecosystem.config.js
    - codedeploy/*
    - scripts/*
    - build/**/*
    - package.json
    - node_modules/**/*
